import { bookForSectors } from "../src/data/sectors.ts";
import { spinCase } from "../src/engine/spin.ts";
import { MODES, MODE_SALT } from "../src/data/modes.ts";
import { buildLeg } from "../src/engine/parlay.ts";
import { edgeOf, scoreOf, settle } from "../src/engine/match.ts";
const arena = spinCase(bookForSectors(["MAJORS","MEME"]), 3, 424242).syms;
const salt = 2 + 424242*3 + MODE_SALT.BLITZ;
const scale = MODES.BLITZ.targetScale;
const mine = arena.map(s => buildLeg(s,"over","EVEN",scale));
const theirs = arena.map(s => buildLeg(s,"under","EVEN",scale));
console.log("arena", arena);
console.log("theirs blitz", scoreOf(theirs, salt, MODES.BLITZ.settleAt), "normal", scoreOf(theirs, salt, MODES.NORMAL.settleAt));
console.log("mine blitz", scoreOf(mine, salt, MODES.BLITZ.settleAt), "normal", scoreOf(mine, salt, MODES.NORMAL.settleAt));
console.log("edge blitz", edgeOf(mine, salt, MODES.BLITZ.settleAt), "normal", edgeOf(mine, salt, MODES.NORMAL.settleAt));
const b = settle(mine, theirs, arena, salt, MODES.BLITZ.settleAt, "You","lexa");
const n = settle(mine, theirs, arena, salt, MODES.NORMAL.settleAt, "You","lexa");
console.log("blitz", b.scoreLine, b.decider);
console.log("normal", n.scoreLine, n.decider);
